import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Mitr } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-nunito",
});

const mitr = Mitr({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-mitr",
});

export const metadata: Metadata = {
  title: "Volunteer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mitr.variable} ${nunito.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
