services:
  db:
    image: postgres:16
    container_name: ku_postgres
    restart: always
    environment:
      POSTGRES_DB: ku_volunteer
      POSTGRES_USER: ku_user
      POSTGRES_PASSWORD: ku_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ku_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:


