# Generated by Django 5.2.5 on 2025-10-21 03:58

import activities.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_add_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the activity', null=True, upload_to=activities.models.activity_cover_image_path),
        ),
        migrations.CreateModel(
            name='ActivityPosterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Poster image for the activity', upload_to=activities.models.activity_poster_image_path)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of the poster (1-4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_images', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Activity Poster Image',
                'verbose_name_plural': 'Activity Poster Images',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'order'), name='unique_activity_poster_order')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text='Reason for rejection or other notes (max 225 characters)', max_length=225)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='activities.activity')),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_decisions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_student_application')],
            },
        ),
    ]
