# Generated by Django 5.2.5 on 2025-10-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_cover_image_activityposterimage_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydeletionrequest',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitydeletionrequest',
            name='organizer_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydeletionrequest',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='activities.activity'),
        ),
    ]
