# Generated by Django 5.2.5 on 2025-10-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activitydeletionrequest_activity_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='activity_id_stored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='activity_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='activities.activity'),
        ),
    ]
