# Generated by Django 5.2.5 on 2025-11-11 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_application_activity_id_stored_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin when activity is rejected', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('upcoming', 'Upcoming'), ('open', 'Open'), ('during', 'During'), ('complete', 'Complete'), ('full', 'Full'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyCheckInCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-character alphanumeric check-in code', max_length=6)),
                ('valid_date', models.DateField(help_text='Date this code is valid for (UTC timezone)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_codes', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Daily Check-in Code',
                'verbose_name_plural': 'Daily Check-in Codes',
                'ordering': ['-valid_date'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'valid_date'), name='unique_activity_daily_code')],
            },
        ),
        migrations.CreateModel(
            name='StudentCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='absent', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Timestamp when student checked in', null=True)),
                ('marked_absent_at', models.DateTimeField(blank=True, help_text='Timestamp when student was automatically marked absent', null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='activities.activity')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Check-in',
                'verbose_name_plural': 'Student Check-ins',
                'ordering': ['-checked_in_at'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'student'), name='unique_activity_student_checkin')],
            },
        ),
    ]
