# Generated by Django 5.2.5 on 2025-11-11 01:49

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id_external',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[config.utils.validate_student_id]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[config.utils.validate_student_year]),
        ),
    ]
